INFO - [2025-03-14 11:58:23,892.892] - [main.py:29 - start_uvicorn] - Starting Uvicorn...
DEBUG - [2025-03-14 11:58:23,894.894] - [proactor_events.py:625 - __init__] - Using proactor: IocpProactor
DEBUG - [2025-03-14 11:58:23,943.943] - [_trace.py:47 - trace] - close.started
DEBUG - [2025-03-14 11:58:23,943.943] - [_trace.py:47 - trace] - close.complete
DEBUG - [2025-03-14 11:58:23,997.997] - [retry.py:286 - from_int] - Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=None, status=None)
INFO - [2025-03-14 11:58:24,004.004] - [posthog.py:22 - __init__] - Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
DEBUG - [2025-03-14 11:58:24,168.168] - [config.py:332 - start] - Starting component System
DEBUG - [2025-03-14 11:58:24,168.168] - [config.py:332 - start] - Starting component Posthog
DEBUG - [2025-03-14 11:58:24,168.168] - [config.py:332 - start] - Starting component OpenTelemetryClient
DEBUG - [2025-03-14 11:58:24,168.168] - [config.py:332 - start] - Starting component SqliteDB
DEBUG - [2025-03-14 11:58:24,188.188] - [config.py:332 - start] - Starting component SimpleQuotaEnforcer
DEBUG - [2025-03-14 11:58:24,188.188] - [config.py:332 - start] - Starting component SimpleRateLimitEnforcer
DEBUG - [2025-03-14 11:58:24,188.188] - [config.py:332 - start] - Starting component LocalSegmentManager
DEBUG - [2025-03-14 11:58:24,189.189] - [config.py:332 - start] - Starting component LocalExecutor
DEBUG - [2025-03-14 11:58:24,189.189] - [config.py:332 - start] - Starting component SegmentAPI
DEBUG - [2025-03-14 11:58:24,197.197] - [_config.py:82 - load_ssl_context] - load_ssl_context verify=True cert=None trust_env=True http2=False
DEBUG - [2025-03-14 11:58:24,198.198] - [_config.py:148 - load_ssl_context_verify] - load_verify_locations cafile='C:\\Users\\marin\\.virtualenvs\\RAG-chatbot-ogCzX7vf\\lib\\site-packages\\certifi\\cacert.pem'
DEBUG - [2025-03-14 11:58:24,207.207] - [segment.py:243 - create_collection] - Collection doc already exists, returning existing collection.
DEBUG - [2025-03-14 11:58:24,214.214] - [_config.py:82 - load_ssl_context] - load_ssl_context verify=True cert=None trust_env=True http2=False
DEBUG - [2025-03-14 11:58:24,214.214] - [_config.py:148 - load_ssl_context_verify] - load_verify_locations cafile='C:\\Users\\marin\\.virtualenvs\\RAG-chatbot-ogCzX7vf\\lib\\site-packages\\certifi\\cacert.pem'
DEBUG - [2025-03-14 11:58:24,222.222] - [_config.py:82 - load_ssl_context] - load_ssl_context verify=True cert=None trust_env=True http2=False
DEBUG - [2025-03-14 11:58:24,223.223] - [_config.py:148 - load_ssl_context_verify] - load_verify_locations cafile='C:\\Users\\marin\\.virtualenvs\\RAG-chatbot-ogCzX7vf\\lib\\site-packages\\certifi\\cacert.pem'
DEBUG - [2025-03-14 11:58:24,232.232] - [segment.py:243 - create_collection] - Collection doc already exists, returning existing collection.
DEBUG - [2025-03-14 11:58:24,239.239] - [_config.py:82 - load_ssl_context] - load_ssl_context verify=True cert=None trust_env=True http2=False
DEBUG - [2025-03-14 11:58:24,240.240] - [_config.py:148 - load_ssl_context_verify] - load_verify_locations cafile='C:\\Users\\marin\\.virtualenvs\\RAG-chatbot-ogCzX7vf\\lib\\site-packages\\certifi\\cacert.pem'
DEBUG - [2025-03-14 11:58:24,248.248] - [_config.py:82 - load_ssl_context] - load_ssl_context verify=True cert=None trust_env=True http2=False
DEBUG - [2025-03-14 11:58:24,249.249] - [_config.py:148 - load_ssl_context_verify] - load_verify_locations cafile='C:\\Users\\marin\\.virtualenvs\\RAG-chatbot-ogCzX7vf\\lib\\site-packages\\certifi\\cacert.pem'
DEBUG - [2025-03-14 11:58:24,692.692] - [connectionpool.py:1049 - _new_conn] - Starting new HTTPS connection (1): us.i.posthog.com:443
DEBUG - [2025-03-14 11:58:25,107.107] - [connectionpool.py:544 - _make_request] - https://us.i.posthog.com:443 "POST /batch/ HTTP/1.1" 200 15
